"""Concrete tensor sizes + inputs for one benchmark point."""

import uuid as _uuid
from typing import Annotated, Dict, Literal, Optional, Union

from pydantic import Field

from .utils import BaseModelWithDocstrings, NonEmptyString, PositiveInt


class RandomInput(BaseModelWithDocstrings):
    """Input tensor generated by the benchmark harness (bounded uniform random)."""

    type: Literal["random"]


class ScalarInput(BaseModelWithDocstrings):
    """Scalar (non-tensor) input with an explicit constant value."""

    type: Literal["scalar"]
    value: Union[int, float, bool]


class BytesInput(BaseModelWithDocstrings):
    """uint8 byte-buffer input with a structural layout (for sentinel/string loops).

    - ``raw``: uniform random bytes in [1, 100] (no NUL) — for byte-scan loops
      whose semantics depend only on byte values (e.g. whitespace word-count).
    - ``cstrings``: random non-NUL bytes [1, 100] with NUL terminators sprinkled in
      and a guaranteed trailing NUL — concatenated null-terminated strings for
      strlen/strcmp-style loops that walk to a sentinel `lmt`/`end` pointer.
    """

    type: Literal["bytes"]
    layout: Literal["raw", "cstrings"] = "raw"


WorkloadInput = Annotated[
    Union[RandomInput, ScalarInput, BytesInput], Field(discriminator="type")
]


class Workload(BaseModelWithDocstrings):
    """One workload point: concrete values for a Definition's var axes + per-input specs.

    Every entry in `definition.inputs` must appear in `self.inputs`:
    - `{"type": "random"}` — tensor generated deterministically from uuid seed
    - `{"type": "scalar", "value": v}` — scalar constant (matches definition's shape=null)

    Raises at input-generation time if any definition input is missing.
    """

    axes: Dict[NonEmptyString, PositiveInt]
    """Concrete values for the Definition's var axes (e.g. {'N': 1, 'H': 56, 'W': 56})."""
    inputs: Dict[NonEmptyString, WorkloadInput] = Field(default_factory=dict)
    """Per-input specs: random tensor or scalar constant."""
    uuid: NonEmptyString = Field(default_factory=lambda: _uuid.uuid4().hex)
    """Stable identifier so traces can be joined to workloads across runs."""
    tags: Dict[str, str] = Field(default_factory=dict)
    description: Optional[str] = None


__all__ = ["RandomInput", "ScalarInput", "BytesInput", "WorkloadInput", "Workload"]
