"""Concrete tensor sizes + inputs for one benchmark point."""

import uuid as _uuid
from typing import Annotated, Dict, Literal, Optional, Union

from pydantic import Field

from .utils import BaseModelWithDocstrings, NonEmptyString, PositiveInt


class RandomInput(BaseModelWithDocstrings):
    """Input tensor generated by the benchmark harness (bounded uniform random)."""

    type: Literal["random"]


class ScalarInput(BaseModelWithDocstrings):
    """Scalar (non-tensor) input with an explicit constant value."""

    type: Literal["scalar"]
    value: Union[int, float, bool]


class BytesInput(BaseModelWithDocstrings):
    """uint8 byte-buffer input with a structural layout (for sentinel/string loops).

    - ``raw``: uniform random bytes in [1, 100] (no NUL) — for byte-scan loops
      whose semantics depend only on byte values (e.g. whitespace word-count).
    - ``cstrings``: random non-NUL bytes [1, 100] with NUL terminators sprinkled in
      and a guaranteed trailing NUL — concatenated null-terminated strings for
      strlen/strcmp-style loops that walk to a sentinel `lmt`/`end` pointer.
    - ``ggml_q4_K`` / ``ggml_q5_K`` / ``ggml_q6_K`` / ``ggml_q8_0``: a 2-D
      [N, K_bytes] weight matrix of real ggml block rows (K_bytes = K/256 *
      {144, 176, 210}, or K/32 * 34 for Q8_0) --
      realistic random k-quant weights (dequantized values O(0.01-0.1)) built
      by the LlamaCppDataset repack helpers, for layout=ggml gemm definitions.
    """

    type: Literal["bytes"]
    layout: Literal["raw", "cstrings", "ggml_q4_K", "ggml_q5_K", "ggml_q6_K", "ggml_q8_0"] = "raw"


class TensorInput(BaseModelWithDocstrings):
    """Input tensor read from a file in the trace warehouse instead of generated.

    For definitions whose numerics depend on the *distribution* of the input, not just
    its shape — k-quant gemms are the canonical case: a real LLM hidden state has a few
    channels one to two orders of magnitude larger than the rest, and a kernel that
    quantizes activations per row rather than per block loses those small values. Random
    inputs hide that completely, so a kernel can pass an SQNR gate on random data and
    still wreck the model. `path` is relative to the trace root (e.g.
    "tensors/gemm/<definition>/act_M64_call0.npy"); the loaded array must match the
    definition's declared shape and dtype for the workload's axes.
    """

    type: Literal["tensor"]
    path: NonEmptyString
    source: Optional[str] = None
    """Free-text provenance, e.g. "Qwen3.5-4B-Q4_K_M blk.8.ffn_gate, wikitext-2 chunk 0"."""


WorkloadInput = Annotated[
    Union[RandomInput, ScalarInput, BytesInput, TensorInput], Field(discriminator="type")
]


class Workload(BaseModelWithDocstrings):
    """One workload point: concrete values for a Definition's var axes + per-input specs.

    Every entry in `definition.inputs` must appear in `self.inputs`:
    - `{"type": "random"}` — tensor generated deterministically from uuid seed
    - `{"type": "scalar", "value": v}` — scalar constant (matches definition's shape=null)
    - `{"type": "tensor", "path": p}` — real tensor loaded from the trace warehouse

    Raises at input-generation time if any definition input is missing.
    """

    axes: Dict[NonEmptyString, PositiveInt]
    """Concrete values for the Definition's var axes (e.g. {'N': 1, 'H': 56, 'W': 56})."""
    inputs: Dict[NonEmptyString, WorkloadInput] = Field(default_factory=dict)
    """Per-input specs: random tensor or scalar constant."""
    uuid: NonEmptyString = Field(default_factory=lambda: _uuid.uuid4().hex)
    """Stable identifier so traces can be joined to workloads across runs."""
    tags: Dict[str, str] = Field(default_factory=dict)
    description: Optional[str] = None


__all__ = ["RandomInput", "ScalarInput", "BytesInput", "TensorInput", "WorkloadInput", "Workload"]
